ratovia/osaka_mentor_freemarket

README.md
=> [WIP]database_design

config/unicorn.rb
capistranoを使用して自動デプロイを構成する。
capistrano : https://github.com/capistrano/capistrano
全世界に公開状態にする作業を自動化しオペレーションミスを減らすため。
=> [WIP]Setting capistrano deploy

app/controllers/application_controller.rb
basic認証
全環境basic認証
本番環境を構築次第ローカルで適応されないようにします
環境変数変更します。
=> [WIP]Basic authentication

BEM.md
=> [WIP]create_BEM.md

app/controllers/application_controller.rb, config/deploy.rb, config/deploy/production.rb
BASIC認証（本番環境のみ）
特定の人のみアクセス出来るようにする
作業中にローカルで認証画面が出ると面倒な為
=> [WIP]basic_authentication_only_production_environment

BEM.md
ページ作成時のclassの命名が被らないための規則を決めました。
=> [WIP]edit_BEM.md

app/assets/stylesheets/application.scss, app/assets/stylesheets/edit_profile.scss, app/controllers/welcome_controller.rb, app/views/welcome/useredit.html.haml, config/routes.rb
ユーザプロフィール編集ページを作成しました。
ユーザが任意のタイミングでプロフィールを変更できるようにする為。
=> Create user edit profile

app/assets/stylesheets/application.scss, app/assets/stylesheets/new_item_button.scss, app/views/welcome/_new_item_button.html.haml, app/views/welcome/identification.html.haml, app/views/welcome/index.html.haml, app/views/welcome/mypage.html.haml, app/views/welcome/new_item.html.haml, app/views/welcome/useredit.html.haml
商品出品のボタンを作成しました。
ボタン全体がリンクになっています。
遷移先URLの設定はしていません。
素早く出品画面に遷移出来るようにすることで、
サービス利用促進を図るため。
[![Image from Gyazo](https://i.gyazo.com/8bec019903fb21e4cc3189a94df7e50a.gif)](https://gyazo.com/8bec019903fb21e4cc3189a94df7e50a)
=> Create new item button

app/assets/stylesheets/common.scss, app/assets/stylesheets/finish_main.scss, app/assets/stylesheets/login_main.scss, app/assets/stylesheets/payment_main.scss, app/views/welcome/finish.html.haml, app/views/welcome/login_page.html.haml, app/views/welcome/payment.html.haml
新規登録ページを修正致しました。
主に画面下方のViewが崩れていた為修正致しました。
new
[![Image from Gyazo](https://i.gyazo.com/1337d8ddcb297befe02ccd8eafef52cc.png)](https://gyazo.com/1337d8ddcb297befe02ccd8eafef52cc)
registration
[![Image from Gyazo](https://i.gyazo.com/92de5c37ff8674c49a3058664178bd85.gif)](https://gyazo.com/92de5c37ff8674c49a3058664178bd85)
sms
[![Image from Gyazo](https://i.gyazo.com/981c60441df82ed2e01f355b85e1ab94.png)](https://gyazo.com/981c60441df82ed2e01f355b85e1ab94)
address
[![Image from Gyazo](https://i.gyazo.com/08691e7aa649b22ddb536dacf5d000f1.gif)](https://gyazo.com/08691e7aa649b22ddb536dacf5d000f1)
payment
[![Image from Gyazo](https://i.gyazo.com/6fbc5e4869962607afdbaf013e272c26.gif)](https://gyazo.com/6fbc5e4869962607afdbaf013e272c26)
finish
[![Image from …
=> fix: sign up page

app/assets/stylesheets/mypage.scss, app/views/welcome/_my_page_sidebar.html.haml, app/views/welcome/logout.html.haml
ログアウト機能実装
ログインユーザーがログアウト出来るように致しました。
マイページからログアウト画面へのリンクも追加しました。
[![Image from Gyazo](https://i.gyazo.com/756edb5cff65d1359ddafb52d9818117.gif)](https://gyazo.com/756edb5cff65d1359ddafb52d9818117)
[![Image from Gyazo](https://i.gyazo.com/d9ab679e1a4fa668a940b38a68732bdf.gif)](https://gyazo.com/d9ab679e1a4fa668a940b38a68732bdf)
=> [WIP]logout function

app/views/devise/sessions/new.html.haml
ログインページからログインできるようにしました。
ログアウトした後もユーザーが再ログインして購入、出品できるようにするため。
=> [WIP]Edit login page

app/views/items/_item.html.haml, app/views/shared/_top_page_main.html.haml
itemの部分を部分テンプレート化しました。
ソースコードの可読性を上げるため
=> partial_create

app/controllers/items_controller.rb
軽微な修正、before_action set_itemに適用しないアクションは除きました。
=> fix before_action

app/assets/javascripts/channels/edit_item.js, app/assets/javascripts/item_image_files.js, app/assets/stylesheets/preview.scss, app/controllers/items_controller.rb, app/views/items/edit.html.haml, app/views/items/preview.html.haml, config/routes.rb
商品編集ページを作成しています。
商品削除を実装しました。
ユーザーが出品後に商品を編集できるようにするため。
=> [WIP]Edit item

app/models/user.rb, app/views/devise/registrations/new.html.haml
SNSを利用しての登録時にパスワードが無い為、登録が出来なかったので修正致しました。
##WHY
ユーザーがSNSを利用しての登録が出来ない為修正
=> Sns modification

app/controllers/items_controller.rb, app/views/shared/_top_page_main.html.haml
カテゴリーの一覧表示をメソッドで処理しました。
カテゴリーごとに表示して、ユーザが目的の商品にたどりやすくする
get_category_itemのメソッドが長くなっているので、レビューをお願いします。
=> update category array

config/initializers/omniauth.rb
csrfのセキュリティエラーがリポジトリから消えないので、再度確認します。
https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284
=> csrf resolv check

app/views/shared/_top_page_main.html.haml
画像が一枚も保存されていないときトップページでエラーが発生することを修正しました。
imagesの中身がない場合 - 条件式を追加しました。
=> update toppage list

spec/rails_helper.rb
テストにてdeviseのメソッドを使用できるようにする設定を追加
request specなどにてログインのテストを実施するときに必要なため
=> add devise testing

app/controllers/credits_controller.rb, app/models/credit.rb, spec/controllers/credits_controller_spec.rb
payjpのモックテストを実装した。
credits_controllerのindexアクション、newアクション、createアクション、destroyアクションのテスト実装
モックを使用したテストを実装する指針が必要だったため
=> payjp mock test
